version: '3.1'

services:

  db:
    image: mysql:8.3.0
    container_name: database-imc
    command:
         - --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    container_name: adminer-imc-ihm
    ports:
          - "8081:8080"
